/**
 * AI Conversations Data — hook-only (data lives in backend store).
 *
 * The hook returns seeded conversations / suggested questions for Kumar
 * (usr_001) and empty collections for everyone else.
 *
 * Live AI responses are now generated by the backend `/mocks/ai/respond`
 * endpoint via the `useSendAiMessage()` mutation hook. No mock data or
 * response generators live in the frontend anymore.
 */

"use client";

import { useAppDataContext } from "@/providers/appdata-provider";

/* ═══════════════════════════════════════════════════════════════════
   TYPES
═══════════════════════════════════════════════════════════════════ */

export interface UserMessage {
  role: "user";
  text: string;
}

export interface AiMessage {
  role: "ai";
  text: string;
  list?: string[];
  citations?: string[];
  note?: string;
}

export type ConversationMessage = UserMessage | AiMessage;

interface AiConversationsBundle {
  SEED_CONVERSATION: ConversationMessage[];
  SUGGESTED_QUESTIONS: string[];
}

/* ═══════════════════════════════════════════════════════════════════
   HOOK
═══════════════════════════════════════════════════════════════════ */

export const useAiConversations = (): AiConversationsBundle => {
  const { data } = useAppDataContext();
  const src = (data.aiConversations || {}) as Record<string, unknown>;
  return {
    SEED_CONVERSATION:
      (src.SEED_CONVERSATION as ConversationMessage[]) ?? [],
    SUGGESTED_QUESTIONS: (src.SUGGESTED_QUESTIONS as string[]) ?? [],
  };
};
